In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats import inter_rater as irr
from sklearn import metrics

In [4]:

excel_file_path = "annotatated.xlsx"
column_names = ['Tarun', 'Tanay', 'Isi']

# Read the Excel file into a pandas DataFrame with specified column names
df = pd.read_excel(excel_file_path, header=None, names=column_names)

# Extract the values from the DataFrame and convert to a NumPy array
numpy_array = df.values

# Display the NumPy array
print(numpy_array)


[[0 0 0]
 [0 0 0]
 [0 0 0]
 ...
 [1 1 1]
 [0 0 0]
 [0 0 0]]


## Cohen's Kappa

In [7]:
annotator_1 = numpy_array[:,0]
annotator_2 = numpy_array[:,1]
annotator_3 = numpy_array[:,2]

In [9]:
kappa_1_2 = metrics.cohen_kappa_score(annotator_1, annotator_2)
kappa_1_2

0.43571280204943574

In [10]:
kappa_1_3= metrics.cohen_kappa_score(annotator_1, annotator_3)
kappa_1_3

0.4187230121398493

In [11]:
kappa_2_3 = metrics.cohen_kappa_score(annotator_3, annotator_2)
kappa_2_3

0.3896463868745975

## Fleiss' Kappa

In [11]:
agg = irr.aggregate_raters(numpy_array) # returns a tuple (data, categories)
agg

(array([[3, 0],
        [3, 0],
        [3, 0],
        ...,
        [0, 3],
        [3, 0],
        [3, 0]]),
 array([0, 1]))

In [12]:
irr.fleiss_kappa(agg[0], method='fleiss')

0.40746553787860806